export const DOWNLOAD_DATA_START = 'DOWNLOAD_DATA_START';
export const DOWNLOAD_DATA_SUCCESS = 'DOWNLOAD_DATA_SUCCESS';
export const DOWNLOAD_DATA_FAIL = 'DOWNLOAD_DATA_FAIL';
export const RESET_DATA = 'RESET_DATA';
export const USER_ORDER_TYPE_FILTER = 'USER_ORDER_TYPE_FILTER';
export const USER_FILTER_START = 'USER_FILTER_START';
